name: Android Build Release CI

on:

  push:

#    branches: [ release/1.9.4 ]

    tags:

      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    

    - name: set up JDK

      uses: actions/setup-java@v2

      with:

        java-version: '17'

        distribution: 'adopt'

        cache: gradle

    - name: Retrieve the secret and decode it to a file

      env:

        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

        KEY_PROPERTIES_BASE64: ${{ secrets.KEY_PROPERTIES_BASE64 }}

      run: |

        echo "$KEY_PROPERTIES_BASE64" | base64 --decode > key.properties

        echo "$KEYSTORE_BASE64" | base64 --decode > keystore.jks

    - name: Print root files

      run: ls -l

    - name: Grant execute permission for gradlew

      run: chmod +x gradlew

    - name: Build with Gradle

      run: ./gradlew assembleRelease

    - name: Stop gradle daemon

      run: ./gradlew --stop

    - name: Get Change logs

      id: get-change-logs

      run: |

        CHANGE_LOGS=`ls -r fastlane/metadata/android/en-US/changelogs | head -1`

        echo "CHANGE_LOGS=$CHANGE_LOGS" >> "$GITHUB_OUTPUT"

    - name: Create Release

      id: create_release

      uses: ncipollo/release-action@v1

      with:

        token: ${{ secrets.GITHUB_TOKEN }}

        # tag: ${{ github.ref }}

#        name: Release ${{ github.ref }}

#        tag: v1.9.4-prerelease

#        name: PreRelease v1.9.4

#        commit: release/1.9.4

        draft: false

        prerelease: false

        bodyFile: fastlane/metadata/android/en-US/changelogs/${{ steps.get-change-logs.outputs.CHANGE_LOGS }}

        artifacts: ./app/build/outputs/apk/release/*.apk

        artifactContentType: application/vnd.android.package-archive

        allowUpdates: true

        updateOnlyUnreleased: true
